# This is a basic workflow to help you get started with Actions

name: Service CI Check

# Controls when the workflow will run
on:
  issue_comment:
    types: 
      - created
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check_build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && github.actor == 'sushshring' }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Check comment"
        uses: actions/github-script@v4
        with:
          script: |
            if (context.comment.body.contains("[I AM A BOT] - Buddy build failed.")) {
              github.createCommitStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                sha: context.sha,
                state: failure
              })
            ) else if (context.comment.body.contains("[I AM A BOT] - Buddy build succeeded.")) {
               github.createCommitStatus({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  sha: context.sha,
                  state: success
                })
            }
